<?xml version="1.0" standalone="yes"?>

<!DOCTYPE UserInterface [
  <!ELEMENT UserInterface (Action*, MenuBar, PopupMenu*, ToolBar*)>

  <!ELEMENT Action (Name, Shortcut?, Mnemonic?, ToolTip?, Icon?)>

  <!ELEMENT MenuBar (MenuSection+)>
  <!ELEMENT MenuSection ((Menu | MenuItem)*)>
  <!ELEMENT Menu (Name?, Mnemonic?, Icon?, MenuSection+)>
  <!ELEMENT MenuItem EMPTY>

  <!ELEMENT PopupMenu (MenuSection+)>

  <!ELEMENT ToolBar (ToolBarSection+)>
  <!ELEMENT ToolBarSection (Button+)>
  <!ELEMENT Button EMPTY>

  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Shortcut (#PCDATA)>
  <!ELEMENT Mnemonic (#PCDATA)>
  <!ELEMENT ToolTip (#PCDATA)>
  <!ELEMENT Icon (#PCDATA)>

  <!ATTLIST Action           id       ID           #REQUIRED
                             class    CDATA        #REQUIRED
                             enabled  (true|false) #IMPLIED>

  <!ATTLIST MenuBar          id       ID           #REQUIRED>

  <!ATTLIST Menu             id       ID           #REQUIRED
                             visible  (true|false) #IMPLIED>

  <!ATTLIST MenuSection      id       ID           #REQUIRED>

  <!ATTLIST MenuItem         actionId IDREF                           #REQUIRED
                             type     (menuItem|checkBox|radioButton) #IMPLIED
                             selected (true|false)                    #IMPLIED>

  <!ATTLIST PopupMenu        class    ID           #REQUIRED>

  <!ATTLIST ToolBar          id              ID           #REQUIRED
                             rolloverButtons (true|false) #IMPLIED
                             visible         (true|false) #IMPLIED>

  <!ATTLIST ToolBarSection   id       ID           #REQUIRED>

  <!ATTLIST Button           actionId IDREF        #REQUIRED
                             showText (true|false) #IMPLIED>
]>

<UserInterface>

  <!-- **************************** List Actions here ********************** -->

  <Action id="de.hpi.emfImporter.importEMF" class="de.hpi.emfImporter.actions.ImportEMFAction" enabled="true">
    <Name>Import EMF</Name>
    <Mnemonic>I</Mnemonic>
    <ToolTip>Import a model from an EMF file</ToolTip>
    <Icon>de/hpi/emfImporter/images/none.gif</Icon>
  </Action>

  
  <!-- **************************** Define MenuBar here ********************** -->

  <MenuBar id="mainMenuBar">
      <MenuSection id="importExportMenuSection">
         <Menu id="importExportMenu" visible="true">
            <Name>Import/Export</Name>
            <Mnemonic>I</Mnemonic>

            <MenuSection id="mainMenuBar.importSection">
            	<MenuItem actionId="de.hpi.emfImporter.importEMF"/>
            </MenuSection>

         </Menu>
      </MenuSection>
   </MenuBar>


  <!-- **************************** List PopupMenus here ********************** -->

 
  <!-- **************************** List ToolBars here ********************** -->


</UserInterface>

